"""
Agent 3: PDF Generator (Academic Visual Summary)
----------------------------------------------------
Generates a professional academic PDF with:
  - Title page
  - Structured summary
  - Key contributions
  - Methodology breakdown
  - Results overview
  - Rendered Mermaid diagrams (via mermaid.ink)
"""

import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image as RLImage,
    PageBreak,
    Table,
    TableStyle,
    HRFlowable,
    ListFlowable,
    ListItem,
)

PDF_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "generated_pdfs")
os.makedirs(PDF_DIR, exist_ok=True)

ACCENT = "#4F46E5"  # indigo-600
ACCENT_LIGHT = "#818CF8"
DARK = "#1E1B4B"
GRAY = "#4B5563"
LIGHT_GRAY = "#F3F4F6"


def _build_styles():
    """Professional academic styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        "DocTitle", parent=styles["Title"],
        fontSize=26, leading=32,
        textColor=colors.HexColor(DARK),
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "DocSubtitle", parent=styles["Normal"],
        fontSize=12, textColor=colors.HexColor(ACCENT),
        spaceAfter=24, alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        "SectionHead", parent=styles["Heading1"],
        fontSize=16, leading=20,
        textColor=colors.HexColor(ACCENT),
        spaceBefore=18, spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "SubSection", parent=styles["Heading2"],
        fontSize=13, leading=17,
        textColor=colors.HexColor(DARK),
        spaceBefore=12, spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        "BodyText2", parent=styles["Normal"],
        fontSize=10.5, leading=15,
        textColor=colors.HexColor(GRAY),
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "BulletItem", parent=styles["Normal"],
        fontSize=10.5, leading=15,
        textColor=colors.HexColor(GRAY),
        leftIndent=20, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "DiagramCaption", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#6B7280"),
        alignment=TA_CENTER, spaceAfter=16, spaceBefore=4,
    ))
    styles.add(ParagraphStyle(
        "PaperType", parent=styles["Normal"],
        fontSize=11, textColor=colors.white,
        alignment=TA_CENTER,
    ))

    return styles


def generate_pdf(
    summary_data: dict,
    diagrams: list[dict],
    diagram_images: list[str | None],
    session_id: str,
) -> str:
    """Build a professional academic PDF.

    Args:
        summary_data: dict with keys paper_type, structured_summary,
                      key_contributions, methodology, results
        diagrams: list of dicts with title, diagram_type, mermaid_code, description
        diagram_images: list of file paths to rendered diagram PNGs (or None)
        session_id: unique session identifier
    """
    filename = os.path.join(PDF_DIR, f"storyboard_{session_id}.pdf")
    doc = SimpleDocTemplate(
        filename, pagesize=A4,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
        topMargin=1.5 * cm, bottomMargin=1.5 * cm,
    )
    styles = _build_styles()
    elements = []

    # ═════════════════════════════════════════════
    # TITLE PAGE
    # ═════════════════════════════════════════════
    elements.append(Spacer(1, 1.5 * inch))
    elements.append(Paragraph("Research Visual Summary", styles["DocTitle"]))
    elements.append(Paragraph("Generated by ResearchHub AI", styles["DocSubtitle"]))
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(HRFlowable(width="60%", thickness=2, color=colors.HexColor(ACCENT)))
    elements.append(Spacer(1, 0.4 * inch))

    # Paper type badge
    paper_type = summary_data.get("paper_type", "Research Paper")
    badge_table = Table(
        [[Paragraph(f"<b>{paper_type}</b>", styles["PaperType"])]],
        colWidths=[3.5 * inch],
    )
    badge_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(ACCENT)),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    elements.append(badge_table)
    elements.append(PageBreak())

    # ═════════════════════════════════════════════
    # SECTION 1: STRUCTURED SUMMARY
    # ═════════════════════════════════════════════
    elements.append(Paragraph("1. Structured Summary", styles["SectionHead"]))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
    elements.append(Spacer(1, 6))

    summary_text = summary_data.get("structured_summary", "")
    for para in summary_text.split("\n"):
        para = para.strip()
        if para:
            elements.append(Paragraph(para, styles["BodyText2"]))
    elements.append(Spacer(1, 12))

    # ═════════════════════════════════════════════
    # SECTION 2: KEY CONTRIBUTIONS
    # ═════════════════════════════════════════════
    elements.append(Paragraph("2. Key Contributions", styles["SectionHead"]))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
    elements.append(Spacer(1, 6))

    contributions = summary_data.get("key_contributions", [])
    if isinstance(contributions, list):
        for i, c in enumerate(contributions, 1):
            elements.append(Paragraph(f"<b>{i}.</b> {c}", styles["BulletItem"]))
    elements.append(Spacer(1, 12))

    # ═════════════════════════════════════════════
    # SECTION 3: METHODOLOGY
    # ═════════════════════════════════════════════
    elements.append(Paragraph("3. Methodology", styles["SectionHead"]))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
    elements.append(Spacer(1, 6))

    methodology = summary_data.get("methodology", "")
    for para in methodology.split("\n"):
        para = para.strip()
        if para:
            elements.append(Paragraph(para, styles["BodyText2"]))
    elements.append(Spacer(1, 12))

    # ═════════════════════════════════════════════
    # SECTION 4: RESULTS
    # ═════════════════════════════════════════════
    elements.append(Paragraph("4. Results & Findings", styles["SectionHead"]))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
    elements.append(Spacer(1, 6))

    results = summary_data.get("results", "")
    for para in results.split("\n"):
        para = para.strip()
        if para:
            elements.append(Paragraph(para, styles["BodyText2"]))
    elements.append(PageBreak())

    # ═════════════════════════════════════════════
    # SECTION 5: DIAGRAMS
    # ═════════════════════════════════════════════
    elements.append(Paragraph("5. Technical Diagrams", styles["SectionHead"]))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
    elements.append(Spacer(1, 8))

    for i, diagram in enumerate(diagrams):
        title = diagram.get("title", f"Diagram {i + 1}")
        desc = diagram.get("description", "")

        elements.append(Paragraph(f"5.{i + 1}  {title}", styles["SubSection"]))

        # Try to embed rendered image
        img_path = diagram_images[i] if i < len(diagram_images) else None
        if img_path and os.path.exists(img_path):
            try:
                img = RLImage(img_path, width=6 * inch, height=3.5 * inch, kind="proportional")
                elements.append(img)
                elements.append(Paragraph(f"Figure 5.{i + 1}: {title}", styles["DiagramCaption"]))
            except Exception as e:
                print(f"[PDF] Failed to embed diagram {i + 1}: {e}")
                elements.append(Paragraph(
                    f"<i>[Diagram rendered in web interface]</i>", styles["BodyText2"]))
        else:
            elements.append(Paragraph(
                f"<i>[Diagram rendered in web interface]</i>", styles["BodyText2"]))

        elements.append(Spacer(1, 12))

    # Build PDF
    doc.build(elements)
    return filename
